import './globals.scss'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Test SCSS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
      <meta name="viewport" content="height=device-height, initial-scale=1" />
      </head>
      <body>{children}</body>
    </html>
  )
}
